- name: Mise à jour de la VM AWX locale
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Mise à jour des paquets
      apt:
        upgrade: dist
        autoremove: yes
