---
- name: Mise à jour Debian distante via AWX
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: yes

    - name: Mise à jour complète des paquets
      apt:
        upgrade: dist
        autoremove: yes
